
name: Test JMeter Action

on:
  push:
    branches: [ "jenkins-on-ec2" ]
  
jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
          
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: tests/sample_test.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: jenkins_trigger_github_actions/result.jtl
