name: trigger jenkins job
on:
  push: 
    branches: [jenkins-on-ec2]
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         jenkins_home: jenkins_home
     - run: |
          curl \
            -X GET \
             http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/crumbIssuer/api/json
          curl \
            -X POST \
             http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/job/job-07092022/buildWithParameters \
             --data token=1116e4d9dd7a0d4dab73d45d96e9b5fb97 \
             --user pulkit_apisero:admin 
             -H 'Jenkins-Crumb: 1116e4d9dd7a0d4dab73d45d96e9b5fb97'
