name: CI
on:
  push:
    branches: [ "jenkins-on-ec2" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Latest_Crumb
        run: |
            jenkins_data= $(curl -X GET http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/crumbIssuer/api/json --user pulkit_apisero:admin --data token=1116e4d9dd7a0d4dab73d45d96e9b5fb97)
