name: trigger jenkins job
on:
  push: 
    branches: [jenkins-on-ec2]
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:  "http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
          jenkins-job: "jenkins-job-2-sep" # The name of the jenkins job to run
          jenkins-username: pulkit_apisero # user name for accessing jenkins
          jenkins-pat: ${{ secrets.JENKINS_TOKEN}} # personal Access token for accessing Jenkins
          poll-time: 10 # how often (seconds) to poll the jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging
