name: CI
on:
  push:
    branches: [ "jenkins-on-ec2" ]
env:
  jenkins_data: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/crumbIssuer/api/json '
        method: 'GET'
        username: 'pulkit_apisero'
        password: 'admin'
    - name: Show Response
      id: myRequest
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
#     - name: Run Latest_Crumb1
#       run: |
#           jenkins_data= $jenkins_data
#           echo "jenkins_data"
#           Latest_Crumb_ID=$( echo "$jenkins_data" | jq -r '.[0].crumb' )
#           echo "Latest_Crumb_ID: Latest Crumb ID is : $Latest_Crumb_ID" 
#           echo ::set-output name=Latest_Crumb_ID::$Latest_Crumb_ID  
