name: CI
on:
  push:
    branches: [ "jenkins-on-ec2" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Run Latest_Crumb1
        run: |
          jenkins_data= $(curl http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080/crumbIssuer/api/json --user pulkit_apisero:admin) \
          Latest_Crumb_ID=$(echo "$jenkins_data" | jq -r '.[0].crumb') \
          echo "Latest_Crumb_ID: Latest Crumb ID is : $Latest_Crumb_ID" \
          echo ::set-output name=Latest_Crumb_ID::$Latest_Crumb_ID  
